In [21]:
from manifm.manifolds.hyperbolic import PoincareBall
import matplotlib.pyplot as plt
import torch

dim = 2
mean = torch.zeros(dim)
std = 0.1

manifold = PoincareBall()
#uniform =manifold.random_base(batch_size=16, dim=2)
#plt.scatter(uniform[:,0], uniform[:,1])

x1 = PoincareBall().wrapped_normal(dim, mean=mean, std=std)
x2 = PoincareBall().wrapped_normal(dim, mean=mean, std=std)
x3 = PoincareBall().wrapped_normal(dim, mean=mean, std=std)
x = torch.stack([x1, x2, x3], dim=0)
origin = torch.zeros_like(x)
a = PoincareBall().dist(origin, x)
print(x,a, origin)

tensor([[-0.0577,  0.0148],
        [-0.0108,  0.0466],
        [-0.0305, -0.0497]]) tensor([0.1192, 0.0958, 0.1167]) tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [2]:
import torch
mean = torch.zeros(3)
print(mean)

tensor([0., 0., 0.])


In [ ]:

mean = torch.zeros(4, 2)
std = torch.full((4, 2), 0.3)

        # geoopt wrapped normal supports batch sampling
samples = PoincareBall.wrapped_normal(
        2,
        mean=mean,      # shape [batch_size, dim]
        std=0.3    # scalar std is broadcast
        )

print(samples)

ModuleNotFoundError: No module named 'geoopt.distributions'

In [4]:
from manifm.manifolds import PoincareBall
manifold = PoincareBall()
a = manifold.dist(0, 1)
print(a)

NameError: name 'PoincareBall' is not defined

In [7]:
from manifm.eval_utils import load_model
import torch

checkpoint = "/home/fvaleau/riemannian-fm/outputs/runs/images/fm/2025.12.05/183800/checkpoints/epoch-313_step-0_loss-0.0000.ckpt"

cfg, model = load_model(checkpoint)
print(type(model))
print(model.manifold)          # See which manifold was instantiated
print(model.sample)            # Confirm method exists
print(model.manifold.random_base)

model = model.cpu()
model.eval()
with torch.no_grad():
    samples = model.sample(10, device="cpu")
print(samples.shape)   # torch.Size([10, 512])
print(samples)


/gpfs/home6/fvaleau/riemannian-fm/manifm/eval_utils.py:39: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  chkpnt = torch.load(checkpoint, map_location="cpu")
/gpfs/home6/fval

<class 'manifm.model_pl.ManifoldFMLitModule'>
PoincareBall manifold
<bound method ManifoldFMLitModule.sample of ManifoldFMLitModule(
  (manifold): PoincareBall manifold
  (model): EMA(
    (model): Unbatch(
      (vecfield): ProjectToTangent(
        (vecfield): SequentialDiffEq(
          (layers): ModuleList(
            (0): ConcatLinear_v2(
              (_layer): Linear(in_features=512, out_features=512, bias=True)
              (_hyper_bias): Linear(in_features=1, out_features=512, bias=False)
            )
            (1): TimeDependentSwish(
              (beta): Sequential(
                (0): Linear(in_features=1, out_features=64, bias=True)
                (1): Softplus(beta=1.0, threshold=20.0)
                (2): Linear(in_features=64, out_features=512, bias=True)
                (3): Softplus(beta=1.0, threshold=20.0)
              )
            )
            (2): ConcatLinear_v2(
              (_layer): Linear(in_features=512, out_features=512, bias=True)
             

RuntimeError: accessing `data` under vmap transform is not allowed

In [6]:
from torch.func import vmap
from manifm.manifolds.hyperbolic import PoincareBall

manifold= PoincareBall()
mean = torch.zeros(2)
std = 0.3
dim=2
batch_size = 3

samples = []
for _ in range(batch_size):
    x = manifold.wrapped_normal(dim, mean=mean, std=std)   
    samples.append(x)

all_samples = torch.stack(samples, dim=0)
def sample_one(_):
    return manifold.wrapped_normal(dim, mean=mean, std=std)

inputs = torch.zeros(batch_size, device=mean.device)  
#vmap_samples = vmap(sample_one, randomness="different")(inputs)  # shape [batch_size, dim
print(all_samples)#,vmap_samples)

tensor([[ 0.2566,  0.0081],
        [-0.0875, -0.2164],
        [-0.0547, -0.2514]])
